### PR TITLE
fix referencing constructor params in constructor body (fixes #13)

### LINKED ISSUE #13: Referencing constructor params is not handled
Hi! Thanks for a nice lib!

I am trying to use it in my project, and I've found an issue with constructor params.

Please see a unit test in https://github.com/timocov/ts-transformer-minify-privates/pull/12

It is broken now - https://github.com/mad-gooze/ts-transformer-minify-privates/blob/reference-ctor-params-unit-test/tests/test-cases/reference-ctor-params/input.ts#L5 (`privateField ` is not replaced so resulting code is incorrect)

### PR DESCRIPTION
**Pull request by mad-gooze**

### CODE REVIEW

File: src/properties-minifier.ts [hunk 1]
```diff
@@ -48,6 +48,8 @@ export class PropertiesMinifier {
 			return this.createNewAccessExpression(node, program);
 		} else if (ts.isBindingElement(node)) {
 			return this.createNewBindingElement(node, program);
+		} else if (isConstructorParameterRefernece(node, program)) {
```
Comment (schmidt-sebastian) [inline src/properties-minifier.ts]: Typo in "Refernece", otherwise looks good. Thanks!

Comment (mad-gooze) [reply src/properties-minifier.ts]: thx, fixed the typo
